### ISSUE TITLE
Adaptar a Andiamo.js

### ISSUE THREAD

**Issue by necsoft** [andiamo/fideos#1]
Actualmente yo armé un ejemplo muy pavo de una aplicación que dispersa el trazo que se esta dibujando a los demás clientes. 

![screen shot 2015-10-29 at 14 40 11](https://cloud.githubusercontent.com/assets/1678333/10819905/020a2e4c-7e4b-11e5-86aa-93c88170949c.png)

Actualmente lo que estoy pasando en el evento movement es la posición actual del puntero, el ancho del trazo y el color, esto se puede adaptar a lo que necesitemos.

**Comment by codeanticode** [comment]
Hola Nec, yo había hecho unas pruebas con una version del código de dibujo de andimo.js que adapté para usar en smartphones, que envia el paquete con toda la data pare generar los trazos dinámicos. No lo tengo en github, pero puedo buscarlo y compartirlo, si es que te pueda ser de utilidad.

**Comment by necsoft** [comment]
Estuve viendo el que tenes en github y me pareció que se podía bypassear el evento del mouse o armar una función similar que funcione recibiendo el trazo que tiene que dibujar, asi lo emito a los demas clientes. Si en esta versión que me decís habías armado algo asi, podríamos meterlo aca.

**Comment by codeanticode** [comment]
Lo que habia hecho en su momento usando node y socket.io (y el cliente en p5.js) era con la siguiente funcion:

``` javascript
function sendMouseEvent(e, x, y, p) {
  // Each Socket.IO connection has a unique session id
  var id = socket.io.engine.id;

  // An object to describe the stroke's data
  var data = {
    i: index,
    x: x,
    y: y,
    c: color,
    p: p,
    w: width,
    h: height,
    ev: e
  };

  // println('send event ' + data.ev);

  // send a 'sendMouseEvent' event with data and sessionId to the server
  socket.emit('sendMouseEvent', data, id);
}
```

y las llamadas:

``` javascript
function mousePressed(e) {  
  if (mode == DRAW  && 0 <= mouseX && mouseX < width && 0 <= mouseY && mouseY < height) {
    var pressure = e.force;
    if (startNewGesture(gestureArray, mouseX, mouseY, pressure)) {
      sendMouseEvent(PRESS, mouseX, mouseY, pressure);
    }  
  } 
}

function mouseDragged(e) {
  if (mode == DRAW  && 0 <= mouseX && mouseX < width && 0 <= mouseY && mouseY < height) {
    var pressure = e.force;
    if (addPointToGesture(gestureArray, mouseX, mouseY, pressure, true)) {
      sendMouseEvent(DRAG, mouseX, mouseY, pressure);
    }    
  }
}
```

Nada del otro mundo...

**Comment by necsoft** [comment]
Hey Andrés como va? No sé si viste los últimos commits, estuve adaptando como me dijiste lo de andiamo, pero me encontre con unas dificultades y quería saber si me podías dar una mano, por ahi soy yo que no estoy entendiendo bien. 

Actualmente en la última versión implementé algo similar a lo que comentaste arriba, el problema es que necesito poder crear una instancia por cada usuario que esta dibujando al mismo tiempo, ya que la versión actual funciona, pero solamente si hay una sola persona del otro lado dibujando, si son mas el gesture se pisaría entre ambos mensajes, así que habría que asignarle un id a cada gesture que se esté dibujando y comprobar cada mensaje. Esto también me complica la forma de pasarle los colores con los que estan dibujando los usuarios externos. Le vengo dando vueltas pero no encuentro la forma de hacerlo, podrías echarle un vistazo? Seguramente es una burrada que me estoy mandando yo.

**Comment by codeanticode** [comment]
Hola Nec, todo bien! 

Si entiendo bien el problema, creo que mi solucion fue de registrar un ID unico para cada usuario en la aplicacion servidor en node.js, de manera de que siempre es posible saber que usuario corresponde a cada trazo que llega al servidor. Algo asi:

``` javascript
var users = {};
var displays = {};
var sockets = {};

io.sockets.on('connection', function (socket) {
  socket.on('login', function(data) {
        // new client
        var rank = 0;
        for (var key in users) {
          rank = Math.max(rank, users[key]);
        }
        rank++;
        users[socket.id] = rank;
        sockets[rank] = socket;

        displays[socket.id] = { w: data.w, h: data.h };

        console.log("Client connected " + rank + " " + socket.id);
        console.log(users);
  }
});
```

Entonces, cada vez que llega un nuevo evento de mouse, hago lo siguente:

``` javascript
socket.on('sendMouseEvent', function(data, src) {
    console.log("Received mouse event from client " + src);
    var res = displays[socket.id];
    var rank = users[src];
    if (rank && res && res.w && res.h) {
      // process event data, send to other users...
      var nx = data.x / res.w;
      var ny = data.y / res.h;
      data.x = nx;
     ...
  }
});
```

Esto resolveria el problema?

**Comment by necsoft** [comment]
En parte, porque actualmente yo desde el servidor ya recibo los id's únicos, el tema es que no entiendo como puedo instanciar un gesture por cada uno, porque actualmente yo hago lo siguiente:

``` javascript
socket.on('andiamoMouseEvent', function(data){

    // Debug log
    console.log("data.id: "+data.id + " data.e: " + data.e + " data.x: " + data.x + " data.y: " + data.y);

    /*
    PRESS
    */

    if (data.e === "PRESS") {
        var t0 = startGestureTime = millis();

        var connected = false;
        if (lastGesture && grouping && t0 - lastGesture.t1 < 1000 * MAX_GROUP_TIME) {
            t0 = lastGesture.t0;
            connected = true;
        }

        currGesture = new StrokeGesture(t0, dissapearing, fixed, lastGesture);

        if (connected) {
            lastGesture.next = currGesture;
        }

        addPointToRibbon(data.x,data.y);
    }

    /*
    DRAGGED
    */

    if (data.e === "DRAGGED") {
        addPointToRibbon(data.x, data.y);
    }

    /*
    RELEASED
    */

    if (data.e === "RELEASED"){
        if (currGesture) {
            addPointToRibbon(data.x, data.y);
            currGesture.setLooping(looping);
            currGesture.setEndTime(millis());
            if (currGesture.visible) {
                layers[currLayer].push(currGesture);
            }
            lastGesture = currGesture;
            currGesture = null;
        }
    }


});
```

Puedo hacer un array de currGesture e indexarlo por sus id's, pero como hago para pasarle el addPointToRibbon a un gesture solo? Yo actualmente no tengo otra compu para probar, pero el resultado por lo que creo, sería que entre varios dibujarían un solo gesture. Esa es la parte que me resulta complicada de entender.

**Comment by codeanticode** [comment]
no creo que haya falta de construir los gestures en el servidor, lo unico que es necesario que haga es el broadcast de los eventos a cada cliente. Los clientes deberian ser capazes de diferenciar cada trazo de acuerdo al id unico de cada usuario... o me estoy pasando por alto algo obvio?

**Comment by necsoft** [comment]
La parte del servidor ya esta resuelta, lo que te pasaba es ya de lado del cliente, mientras llamo a Andiamo para poder trazar los gestures externos que las demás personas están dibujando, sería el "on" de lado del cliente. Yo por parte del servidor ya me encargo de enviar y recibir data del mouse, estado, id y color, pero no lo estoy pudiendo asignar sin que se pisen entre ellos. Quizás yo me estoy explicando mal.

**Comment by codeanticode** [comment]
ah ok, entiendo. No podrias crear en cada cliente un diccionario de gestures que utilize el ID del usuario como clave, y llamar addPointToRibbon() del gesture que corresponda a data.id? Un punto importante es que cada cliente solo puede estar dibujando un trazo a la vez, asi que la correspondencia estaria bien definida

**Comment by necsoft** [comment]
Esta última parte no la sabía, solamente se puede dibujar un trazo a la vez? Es decir, sería por turnos? Porque de ser asi no habría problema.

Mi problema es que el addPointToRibbon() no pertenece a un objeto que pueda pasar a diccionario, porque manipula currGesture que es una variable global. Existe alguna forma de pasarle a addPointToRibbon el gesture que tiene que manipular?

Disculpa que te moleste con esto, es que me trabé y prefería preguntarte a vos que lo habías armado. Saludos!

**Comment by codeanticode** [comment]
Cada usuario tiene un solo gesture abierto o activo a la vez, pero no tendría que haber limitación en lo que respecta a cuantos usuarios están dibujando simultáneamente. Lo que yo decía es que, aun le lleguen varios mouse events a un cliente provenientes de distintos usuarios, es posible determinar a que objeto StrokeGesture hay que agregarlos ya que tenemos data.id para diferenciarlos, no? Como cada usuario solo tiene un gesture abierto en cada momento, no hay ambigüedad a la hora de asignar el nuevo evento al trazo de un cliente, ya que cada uno debería tener a lo sumo uno activo.

**Comment by necsoft** [comment]
Los eventos externos (los de tipo "el otro usuario esta dibujando") los creo con las mismas funciones locales con las que se crea el trazo local, de lado del cliente estan agregadas todas las dependencias tal y cual como estaban en andiamo.js.

Si me llegan 3 personas dibujando al mismo tiempo con diferentes id's, yo tengo que seguir usando el mismo addPointToRibbon() para cada uno porque no es un objeto, es un conjunto de funciones y variables globales que operan en base al valor actual de currGesture y otras variables locales, ese es mi problema. No existe uno solo activo, existe el local y las funciones en local que uso para generar el efecto de reconstruir lo que los demás están dibujando, no sé si me estoy explicando bien, pero no tengo forma de hacerlo si no modificamos como funciona el js de andiamo, la verdad es que me esta costando esa parte en particular, lo otro lo puedo seguir.

Encima me esta costando que desde aca no tengo otra compu para testearlo, sino voy a tener que esperar al 19 que llego a Argentina y tengo otra compu mas.

**Comment by codeanticode** [comment]
ok, ocurre que andiamo.js fue escrito como prototipo sin soporte de usuarios multiples, es por eso que todos los trazos se guardan en una lista unica... asi que si, hay que modificar andiamo. Pero no deberia ser dificil, no aclanza con implementar alguna forma de diccionario que asigne el gesture correspondiente a cada user id?

**Comment by necsoft** [comment]
Entiendo eh, no es un reclamo, es simplemente que necesito una mano porque no encuentro la forma de hacerlo, la parte mas estrictamente de web la puedo manejar. Lo veré cuando vuelva a Argentina a ver si encuentro alguna forma de adaptarlo, si se te llega a ocurrir algo avisame.

**Comment by codeanticode** [comment]
ningun problema, voy a ver si alcanzo hoy a hacer unos cambios en el codigo para que funcione con hashmap, tenia una clase de hashamp implementada en JavaScript por ahi dando vueltas.

**Comment by codeanticode** [comment]
Hice los siguientes cambios en el código de andiamo: agregué una clase [HashMap](https://github.com/andiamo/fideos/commit/9f771e27bc5a237cbe9a8adb2400d93e468eec71), y encapsule la lógica de dibujo de los ribbons dentro de la clase [Ribbon](https://github.com/andiamo/fideos/commit/8a9707cfebec3d98158a3a09c3a3bc843791c4b3). Me aseguré que andiamo sigue funcionando después de estos cambios :-)

Con todo esto debería ser relativamente simple resolver el problema, por ejemplo haciendo currGesture, lastGesture, y Ribbon HashMaps con el id de usuario como clave. Que te parece?

**Comment by necsoft** [comment]
Gracias! Genial, ahora lo implemento, disculpa que tardé en responder, fue intercalada la vuelta a Argentina, pero por suerte ya estoy aca!

**Comment by codeanticode** [comment]
Buenismo, te parece que podremos tener una version preliminar funcionando con algunos de los elementos de la interface de Manu para comienzos de diciembre?

**Comment by necsoft** [comment]
Si, solo necesito unos días mas, tengo un par de cosas pero todavía no hice push.
