### ISSUE TITLE
Icono de compartir parcialmente activo

### ISSUE THREAD

**Issue by codeanticode** [andiamo/fideos#13]
Cuando se abre la pagina:

![image](https://cloud.githubusercontent.com/assets/62246/16885173/549509c6-4a9b-11e6-9b35-3b0f843ae13f.png)

**Comment by macramole** [comment]
Me parece que ahí está arreglado, me podés confirmar ?

**Comment by codeanticode** [comment]
si, lo probe en chrome, firefox, y safari y se ve bien
